# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.caching=true

# AndroidX
android.useAndroidX=true
android.nonTransitiveRClass=true

# Don't fail the build if the AGP in use flags compileSdk 36 as "untested".
android.suppressUnsupportedCompileSdk=36

# Kotlin
kotlin.code.style=official
